version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "golang"
    directory: "/"
    schedule:
      interval: "daily"
